/*
 * Bryce Dingwall
 * April 12, 2017
 * Displays values between two given numbers
 */

/**
 *
 * @author brdin1728
 */
public class funLoops extends javax.swing.JFrame {

    /**
     * Creates new form funLoops
     */
    public funLoops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JLabel();
        instructOne = new javax.swing.JLabel();
        instructTwo = new javax.swing.JLabel();
        oneInput = new javax.swing.JTextField();
        twoInput = new javax.swing.JTextField();
        biggieCheese = new javax.swing.JButton();
        outputBar = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileOption = new javax.swing.JMenu();
        helpOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleBar.setFont(new java.awt.Font("Swis721Cyrillic BT", 0, 36)); // NOI18N
        titleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBar.setText("Fun With Boucles");

        instructOne.setText("Starting Number:");

        instructTwo.setText("Ending Number:");

        twoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoInputActionPerformed(evt);
            }
        });

        biggieCheese.setText("Biggie Cheese");
        biggieCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biggieCheeseActionPerformed(evt);
            }
        });

        outputBar.setFont(new java.awt.Font("SouvenirItcTEEDem", 0, 18)); // NOI18N
        outputBar.setForeground(new java.awt.Color(255, 0, 0));

        fileOption.setText("File");
        menuBar.add(fileOption);

        helpOption.setText("Help");
        menuBar.add(helpOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(instructOne)
                                    .addComponent(instructTwo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(twoInput)
                                    .addComponent(oneInput, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(outputBar, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(biggieCheese))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleBar)))
                        .addGap(12, 12, 12)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructOne)
                    .addComponent(oneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructTwo)
                    .addComponent(twoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(biggieCheese)
                .addGap(39, 39, 39)
                .addComponent(outputBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoInputActionPerformed

    private void biggieCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biggieCheeseActionPerformed
        int startValue;
        int lastValue;
        String dun;
        dun = (" ");
        startValue = Integer.parseInt(oneInput.getText());
        lastValue = Integer.parseInt(twoInput.getText());
        for (int i = startValue; i <= lastValue; i++) {
             dun += i;
        }
        outputBar.setText(dun + " ");
    }//GEN-LAST:event_biggieCheeseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funLoops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biggieCheese;
    private javax.swing.JMenu fileOption;
    private javax.swing.JMenu helpOption;
    private javax.swing.JLabel instructOne;
    private javax.swing.JLabel instructTwo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField oneInput;
    private javax.swing.JLabel outputBar;
    private javax.swing.JLabel titleBar;
    private javax.swing.JTextField twoInput;
    // End of variables declaration//GEN-END:variables
}
